blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView

app_name = BlogConfig.name

urlpatterns = [
    path('blogs', cache_page(60)(BlogListView.as_view()), name='blogs'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('distribution.urls', namespace='distribution')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import (LoginView, LogoutView, UserRegisterView,
                         confirm_email, recover_password, UserListView, toggle_active)

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', UserListView.as_view(), name='users'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', LogoutView.as_view(), name='profile'),
    path('confirm-register/<str:token>/', confirm_email, name='confirm_email'),
    path('recover_password/', recover_password, name='recover_password'),
    path('toggle_active_user/<int:pk>', toggle_active, name='toggle_active_user')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from distribution.models import NULLABLE


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Email')
    token = models.CharField(max_length=35, verbose_name='token', **NULLABLE)
    is_active = models.BooleanField(default=False, verbose_name='Статус')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        permissions = [
            ('set_active', 'Can active users')
        ]

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from distribution.forms import StyleFormMixin
from users.models import User


class LoginForm(StyleFormMixin, AuthenticationForm):
    class Meta:
        model = User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')

users/views.py
import secrets

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView

from users.forms import LoginForm, UserRegisterForm
from users.models import User


class LoginView(BaseLoginView):
    template_name = 'users/login.html'
    form_class = LoginForm


class LogoutView(BaseLogoutView):
    template_name = 'users/login.html'


class UserListView(LoginRequiredMixin, ListView):
    model = User


class UserRegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        token = secrets.token_hex(16)
        user = form.save()
        user.token = token
        host = self.request.get_host()
        link = f'http://{host}/users/confirm-register/{token}'
        message = f'Вы успешно зарегистрировались на нашем сайте! Подтвердите регистрацию по ссылке:\n{link}'
        send_mail('Подтвердите регистрацию', message, settings.EMAIL_HOST_USER, [user.email])
        return super().form_valid(form)


def confirm_email(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('distribution:home'))


def recover_password(request):
    template_name = 'users/recover.html'

    if request.method == 'POST':
        email = request.POST.get('email')
        user = User.objects.get(email=email)
        new_password = secrets.token_hex(6)
        password = make_password(new_password)
        user.password = password
        user.save()
        message = f'Ваш временный пароль\n{new_password}'
        send_mail('Восстановление пароля', message, settings.EMAIL_HOST_USER, [user.email])
        return redirect(reverse('distribution:home'))
    return render(request, template_name)


def toggle_active(request, pk):
    user = get_object_or_404(User, pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True
    user.save()
    return redirect(reverse('users:users'))

users/templates/users/login.html
{% extends 'distribution/base.html' %}
{% block content %}
{% load tags %}
<div class="row">
    <div class="col-3"></div>
    <div class="card col-6">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <a href="{% url 'users:recover_password' %}" class="nav-link">Забыл пароль</a>
                <p></p>
                <button type="submit" class="btn btn-success">
                    Войти
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/recover.html
{% extends 'distribution/base.html' %}
{% block content %}
{% load tags %}
<div class="row">
    <div class="col-3"></div>
    <div class="card col-6">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="Email" class="form-label">Адрес электронной почты</label>
                    <input name="email" type="email" class="form-control" id="Email" aria-describedby="emailHelp">
                    <div id="emailHelp" class="form-text">Мы никогда никому не передадим вашу электронную почту.</div>
                </div>
                <p></p>
                <button type="submit" class="btn btn-success">
                    Отправить пароль
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'distribution/base.html' %}
{% block content %}
{% load tags %}
<div class="row">
    <div class="col-3"></div>
    <div class="card col-6">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">
                    Зарегистрировать
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'distribution/base.html' %}
{% load tags %}
{% block content %}
<div class="container-lg">
    <div class="row container">
        {% for object in object_list %}
        <div class="col-4 mb-4">
            <div class="card mb-4 rounded-3">
                <div class="card-header py-3  text-center">
                    <h4 class="my-0 fw-normal">{{ object.email }}</h4>
                </div>
                <div class="card-body">
                    {% if object.is_active %}
                        <p><a class="link mb-2" href="{% url 'users:toggle_active_user' object.pk %}">Активен</a></p>
                    {% else %}
                        <p><a class="link mb-2" href="{% url 'users:toggle_active_user' object.pk %}">Неактивен</a></p>
                    {% endif %}
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}