blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView

app_name = BlogConfig.name

urlpatterns = [
    path('blogs', cache_page(60)(BlogListView.as_view()), name='blogs'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('distribution.urls', namespace='distribution')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

distribution/urls.py
from django.urls import path

from distribution.apps import DistributionConfig
from distribution.views import (ClientCreateView, ClientDeleteView,
                                ClientDetailView, ClientListView,
                                ClientUpdateView, HomePageView,
                                MailingSettingsCreateView,
                                MailingSettingsDeleteView,
                                MailingSettingsListView,
                                MailingSettingsUpdateView, MessageCreateView,
                                MessageDeleteView, MessageDetailView,
                                MessageListView, MessageUpdateView,
                                set_timezone, MailingLogListView, toggle_active)

app_name = DistributionConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('create_message/', MessageCreateView.as_view(), name='create_message'),
    path('update_message/<int:pk>', MessageUpdateView.as_view(), name='update_message'),
    path('delete_message/<int:pk>', MessageDeleteView.as_view(), name='delete_message'),
    path('message/<int:pk>', MessageDetailView.as_view(), name='message'),
    path('messages', MessageListView.as_view(), name='messages'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('update_client/<int:pk>', ClientUpdateView.as_view(), name='update_client'),
    path('delete_client/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),
    path('client/<int:pk>', ClientDetailView.as_view(), name='client'),
    path('clients', ClientListView.as_view(), name='clients'),
    path('create_distribution/', MailingSettingsCreateView.as_view(), name='create_distribution'),
    path('update_distribution/<int:pk>', MailingSettingsUpdateView.as_view(), name='update_distribution'),
    path('delete_distribution/<int:pk>', MailingSettingsDeleteView.as_view(), name='delete_distribution'),
    path('distributions', MailingSettingsListView.as_view(), name='distributions'),
    path('logs', MailingLogListView.as_view(), name='logs'),
    path('set_timezone', set_timezone, name='set_timezone'),
    path('toggle_active/<int:pk>', toggle_active, name='toggle_active')
]

distribution/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(verbose_name='Email')
    surname = models.CharField(max_length=64, verbose_name='Фамилия', **NULLABLE)
    name = models.CharField(max_length=64, verbose_name='Имя', **NULLABLE)
    patronymic = models.CharField(max_length=64, verbose_name='Отчество', **NULLABLE)
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    title = models.CharField(max_length=100, verbose_name='Тема письма')
    text = models.TextField(verbose_name='Письмо')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class MailingSettings(models.Model):
    DAILY = "Раз в день"
    WEEKLY = "Раз в неделю"
    MONTHLY = "Раз в месяц"

    PERIODICITY_CHOICES = [
        (DAILY, "Раз в день"),
        (WEEKLY, "Раз в неделю"),
        (MONTHLY, "Раз в месяц"),
    ]

    CREATED = 'Создана'
    STARTED = 'Запущена'
    COMPLETED = 'Завершена'

    STATUS_CHOICES = [
        (COMPLETED, "Завершена"),
        (CREATED, "Создана"),
        (STARTED, "Запущена"),
    ]

    start_time = models.DateTimeField(verbose_name='Дата начала рассылки')
    end_time = models.DateTimeField(verbose_name='Дата конца рассылки')
    periodicity = models.CharField(max_length=20, choices=PERIODICITY_CHOICES, verbose_name='Периодичность')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=CREATED, verbose_name='Статус рассылки')
    is_active = models.BooleanField(default=True, verbose_name='Статус работы')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, default=None, verbose_name='Сообщение')
    clients = models.ManyToManyField(Client, verbose_name='Клиенты рассылки')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return f'{self.message} {self.periodicity}'

    class Meta:
        verbose_name = 'Настройки рассылки'
        verbose_name_plural = 'Настройки рассылки'
        permissions = [
            ('set_active', 'Can active mailingsettings')
        ]


class MailingLog(models.Model):
    time = models.DateTimeField(verbose_name='Дата и время создания лога', auto_now_add=True)
    status = models.BooleanField(verbose_name='Статус попытки')
    server_response = models.CharField(max_length=1000, verbose_name='Ответ почтового сервера', **NULLABLE)
    mailing = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='Рассылка', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return f'{self.time} {self.status}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'
        ordering = ('-time',)

distribution/forms.py
from django import forms
from django.forms import DateTimeInput

from distribution.models import Client, MailingSettings, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.widgets.SelectMultiple):
                field.widget.attrs['class'] = 'form-control select2 select2-multiple'
            elif isinstance(field.widget, forms.widgets.Select):
                field.widget.attrs['class'] = 'form-control select2'
            elif isinstance(field, forms.DateTimeField):
                field.widget = DateTimeInput(
                    attrs={'class': 'form-control flatpickr-basic',
                           "placeholder": "ДД.ММ.ГГГГ ЧЧ:ММ:СС",
                           "type": "datetime-local"
                           }
                )
            else:
                field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('owner',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('owner',)


class MailingSettingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        exclude = ('status', 'owner',)


class MailingSettingsFormUpdate(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        exclude = ('status', 'owner',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.DateTimeField):
                field.widget = DateTimeInput(
                    attrs={'class': 'form-control flatpickr-basic',
                           "placeholder": "ДД.ММ.ГГГГ ЧЧ:ММ:СС",
                           "type": "datetime"}
                )

distribution/views.py
import pytz
from apscheduler.schedulers.background import BackgroundScheduler
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)
from distribution.forms import ClientForm, MailingSettingsForm, MessageForm, MailingSettingsFormUpdate
from distribution.models import Client, MailingSettings, Message, MailingLog
from distribution.services import cache_extra_context, apscheduler


class BindOwnerMixin:

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_staff:
            return self.model.objects.all().select_related("owner")
        else:
            return self.model.objects.filter(owner=self.request.user).select_related("owner")


class UpdateMixin:
    def get_form_class(self):
        user = self.request.user
        if user.groups.filter(name='менеджер').exists():
            return HttpResponseForbidden
        if user == self.object.owner or user.is_superuser:
            return self.form_class
        raise HttpResponseForbidden


class LimitedFormMixin:
    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
            my_form_class = form_class(**self.get_form_kwargs())
            my_form_class["clients"].field.queryset = Client.objects.filter(owner=self.request.user)
            my_form_class["message"].field.queryset = Message.objects.filter(owner=self.request.user)
            return my_form_class


class APSchedulerMixin:
    def get(self, *args, **kwargs):
        scheduler = BackgroundScheduler(timezone=settings.TIME_ZONE)
        apscheduler(scheduler)
        return super().get(self, *args, **kwargs)


class HomePageView(APSchedulerMixin, TemplateView):
    template_name = "distribution/index.html"

    def get_context_data(self, **kwargs):
        return cache_extra_context()


class MessageCreateView(LoginRequiredMixin, BindOwnerMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('distribution:messages')


class MessageUpdateView(LoginRequiredMixin, BindOwnerMixin, UpdateMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('distribution:messages')


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('distribution:messages')


class MessageDetailView(LoginRequiredMixin, BindOwnerMixin, DetailView):
    model = Message


class MessageListView(APSchedulerMixin, LoginRequiredMixin, BindOwnerMixin, ListView):
    model = Message


class ClientCreateView(LoginRequiredMixin, BindOwnerMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('distribution:clients')


class ClientUpdateView(LoginRequiredMixin, BindOwnerMixin, UpdateMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('distribution:clients')


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('distribution:clients')


class ClientDetailView(LoginRequiredMixin, BindOwnerMixin, DetailView):
    model = Client


class ClientListView(APSchedulerMixin, LoginRequiredMixin, BindOwnerMixin, ListView):
    model = Client


class MailingSettingsCreateView(LoginRequiredMixin, BindOwnerMixin, LimitedFormMixin, CreateView):
    model = MailingSettings
    form_class = MailingSettingsForm
    success_url = reverse_lazy('distribution:distributions')


class MailingSettingsUpdateView(LoginRequiredMixin, BindOwnerMixin, LimitedFormMixin, UpdateMixin, UpdateView):
    model = MailingSettings
    form_class = MailingSettingsFormUpdate
    success_url = reverse_lazy('distribution:distributions')


class MailingSettingsDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingSettings
    success_url = reverse_lazy('distribution:distributions')


class MailingSettingsListView(APSchedulerMixin, LoginRequiredMixin, BindOwnerMixin, ListView):
    model = MailingSettings


class MailingLogListView(APSchedulerMixin, LoginRequiredMixin, BindOwnerMixin, ListView):
    model = MailingLog


def set_timezone(request):
    if request.method == 'POST':
        request.session['django_timezone'] = request.POST['timezone']
        mailings: QuerySet = MailingSettings.objects.all()
        for mailing in mailings:
            mailing.start_time = timezone.localtime(mailing.start_time)
        return HttpResponseRedirect(reverse_lazy('distribution:home'))
    else:
        return render(request, 'distribution/timezone.html', {'timezones': pytz.common_timezones})


def toggle_active(request, pk):
    mailing = get_object_or_404(MailingSettings, pk=pk)
    if mailing.is_active:
        mailing.is_active = False
    else:
        mailing.is_active = True
    mailing.save()
    return redirect(reverse('distribution:distributions'))

distribution/templates/distribution/client_detail.html
{% extends 'distribution/base.html' %}
{% load tags %}
{% block content %}
<div class="container-lg">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6 mb-4">
            <div class="card mb-4 rounded-3">
                <div class="card-header py-3  text-center">
                    <h4 class="my-0 fw-normal">{{ object.email }}</h4>
                </div>
                <div class="card-body">
                    <p>Фамилия - {% if object.surname %}{{object.surname}}{% else %}Не указано{% endif %}</p>
                    <p>Имя - {% if object.name %}{{object.name}}{% else %}Не указано{% endif %}</p>
                    <p>Отчество - {% if object.patronymic %}{{object.patronymic}}{% else %}Не указано{% endif %}</p>
                    <p>Комментарий - {% if object.comment %}{{object.comment}}{% else %}Не указано{% endif %}</p>
                    <div class="card-footer">
                        <div class="row">
                            <div class="btn-group" role="group">
                                <a type="button" class="btn btn-secondary col-4"
                                   href="{% url 'distribution:update_client' object.pk %}">Изменить</a>
                                <a type="button" class="btn btn-danger col-4"
                                   href="{% url 'distribution:delete_client' object.pk %}">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/client_list.html
{% extends 'distribution/base.html' %}
{% load tags %}
{% block content %}
<div class="container-lg">
    <div class="row container">
        <div class="col-4"></div>
        <div class="col-4 text-center">
            <a type="button" class="btn btn-success mb-5 rounded-3 col-12"
               href="{% url 'distribution:create_client' %}">Создать клиента</a>
        </div>
        <div class="col-4"></div>
        {% for object in object_list %}
        <div class="col-4 mb-4">
            <div class="card mb-4 rounded-3">
                <div class="card-header py-3  text-center">
                    <h4 class="my-0 fw-normal">{{ object.email }}</h4>
                </div>
                <div class="card-body">
                    <p>Фамилия - {% if object.surname %}{{object.surname}}{% else %}Не указано{% endif %}</p>
                    <p>Имя - {% if object.name %}{{object.name}}{% else %}Не указано{% endif %}</p>
                    <p>Отчество - {% if object.patronymic %}{{object.patronymic}}{% else %}Не указано{% endif %}</p>
                    <p>Комментарий - {% if object.comment %}{{object.comment}}{% else %}Не указано{% endif %}</p>
                    {% if perms.distribution.change_mailingsettings or user == object.owner %}
                    <div class="card-footer">
                        <div class="row">
                            <div class="btn-group" role="group">
                                <a type="button" class="btn btn-secondary col-4"
                                   href="{% url 'distribution:update_client' object.pk %}">Изменить</a>
                                <a type="button" class="btn btn-danger col-4"
                                   href="{% url 'distribution:delete_client' object.pk %}">Удалить</a>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}

distribution/templates/distribution/index.html
{% extends 'distribution/base.html' %}
{% block content %}
{% load static %}
{% load tags %}
<div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true"
                aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg"
                 aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
                <rect width="100%" height="100%" fill="var(--bs-secondary-color)"/>
            </svg>
            <div class="container">
                <div class="carousel-caption text-start">
                    <img src="{% static 'img/tozhe.jpg' %}">
                    <h1>Бэкенд-разработчик</h1>
                    <p class="opacity-75">Я тоже своего рода</p>
                    <p><a class="btn btn-lg btn-primary" href="{% url 'distribution:messages' %}">Создай сообщение</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg"
                 aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">

                <rect width="100%" height="100%" fill="var(--bs-secondary-color)"/>
            </svg>
            <div class="container">

                <div class="carousel-caption">
                    <img src="{% static 'img/ustal.jpg' %}">
                    <h1>Фронтенд</h1>
                    <p>Верстать этот ваш</p>
                    <p><a class="btn btn-lg btn-primary" href="{% url 'distribution:clients' %}">Знай своего клиента</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg"
                 aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
                <rect width="100%" height="100%" fill="var(--bs-secondary-color)"/>
            </svg>
            <div class="container">
                <div class="carousel-caption text-end">
                    <img src="{% static 'img/staralis.jpg' %}">
                    <h1>Старались</h1>
                    <p>Честно говоря, времени потрачено не мало</p>
                    <p><a class="btn btn-lg btn-primary" href="{% url 'distribution:distributions' %}">Управляй рассылками</a></p>
                </div>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<div class="container marketing">
    <div class="row">
        {% for object in object_list %}
        <div class="col-lg-4">
            <img src="{% media object.preview %}" class="card-img-top mb-2">
            <h2 class="fw-normal">{{object.title}}</h2>
            <p>{{object.content|string_slice}}</p>
            <p><a class="btn btn-secondary" href="{% url 'blog:blogs' %}">К нам в блог</a></p>
        </div>
        {% endfor %}
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
            <h3 class="featurette-heading fw-normal lh-4">Количество рассылок всего</h3>
            <h1 class="featurette-heading fw-normal lh-1">
                <span class="text-body-secondary">{{distributions}}</span></h1>
        </div>
        <div class="col-md-5">
            <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500"
                 height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="var(--bs-secondary-bg)"/>
                <text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text>
            </svg>
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7 order-md-2">
            <h3 class="featurette-heading fw-normal lh-4">Количество активных рассылок</h3>
            <h1 class="featurette-heading fw-normal lh-1">
                <span class="text-body-secondary">{{distributions_active}}</span></h1>
        </div>
        <div class="col-md-5 order-md-1">
            <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500"
                 height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="var(--bs-secondary-bg)"/>
                <text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text>
            </svg>
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
            <h3 class="featurette-heading fw-normal lh-4">Уникальных клиентов</h3>
            <h1 class="featurette-heading fw-normal lh-1">
                <span class="text-body-secondary">{{clients_unique}}</span></h1>
        </div>
        <div class="col-md-5">
            <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500"
                 height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="var(--bs-secondary-bg)"/>
                <text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text>
            </svg>
        </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

</div><!-- /.container -->
{% endblock %}

distribution/templates/distribution/mailinglog_list.html
{% extends 'distribution/base.html' %}
{% load tags %}
{% block content %}
<div class="container-lg mt-5">
    <div class="row container">
        {% for object in object_list %}
        <div class="col-12">
            <div class="card mb-4 rounded-3">
                <div class="card-header py-3  text-center">
                    {% if perms.distribution.change_mailingsettings or user == object.mailing.owner %}
                    <a class="link mb-2" href="{% url 'distribution:update_distribution' object.mailing.pk %}">
                        <h4 class="my-0 fw-normal">{{object.mailing}}</h4></a>
                    {% else %}
                    <h4 class="my-0 fw-normal">{{object.mailing}}</h4>
                    {% endif %}
                </div>
                <div class="card-body">
                    <p>{{object.time}} {{object.server_response}}</p>
                    {% if user.is_staff %}
                    <p>{{object.mailing.owner}}</p>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

distribution/templates/distribution/mailingsettings_list.html
{% extends 'distribution/base.html' %}
{% load tags %}
{% block content %}
<div class="container-lg">
    <div class="row container">
        <div class="col-4"></div>
        <div class="col-4 text-center">
            <a type="button" class="btn btn-success mb-5 rounded-3 col-12"
               href="{% url 'distribution:create_distribution' %}">Создать рассылку</a>
        </div>
        <div class="col-4"></div>
        {% for object in object_list %}
        <div class="col-4 mb-4">
            <div class="card mb-4 rounded-3">
                <div class="card-header py-3  text-center">
                    <h4 class="my-0 fw-normal">{{object.status}}</h4>
                </div>
                <div class="card-body">
                    <p>Начало - {{object.start_time}}</p>
                    <p>Конец - {{object.end_time}}</p>
                    <p>Периодичность - {{object.periodicity}}</p>
                    <p>Сообщение - <a class="link mb-2" href="{% url 'distribution:message' object.message.pk %}">{{object.message}}</a>
                    </p>
                    <p>Получатели -
                        {% for client in object.clients.all %}
                        <a class="link mb-2" href="{% url 'distribution:client' client.pk %}">{{client}}</a>{% if not forloop.last %},{% endif %}
                        {% endfor %}
                    </p>
                    {% if perms.distribution.set_active or user == object.owner %}
                    {% if object.is_active %}
                        <p><a class="link mb-2" href="{% url 'distribution:toggle_active' object.pk %}">Активно</a></p>
                    {% else %}
                        <p><a class="link mb-2" href="{% url 'distribution:toggle_active' object.pk %}">Неактивно</a></p>
                    {% endif %}
                    {% endif %}
                    {% if perms.distribution.change_mailingsettings or user == object.owner %}
                    <div class="card-footer">
                        <div class="row">
                            <div class="btn-group" role="group">
                                <a type="button" class="btn btn-secondary col-4"
                                   href="{% url 'distribution:update_distribution' object.pk %}">Изменить</a>
                                <a type="button" class="btn btn-danger col-4"
                                   href="{% url 'distribution:delete_distribution' object.pk %}">Удалить</a>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}

distribution/templates/distribution/message_detail.html
{% extends 'distribution/base.html' %}
{% load tags %}
{% block content %}
<div class="container-lg">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6 mb-4">
            <div class="card mb-4 rounded-3">
                <div class="card-header py-3  text-center">
                    <h4 class="my-0 fw-normal">{{object.title}}</h4>
                </div>
                <div class="card-body">
                    <p>
                        {{object.text|string_slice}}
                    </p>
                    <div class="card-footer">
                        <div class="row">
                            <div class="btn-group" role="group">
                                <a type="button" class="btn btn-secondary col-4"
                                   href="{% url 'distribution:update_message' object.pk %}">Изменить</a>
                                <a type="button" class="btn btn-danger col-4"
                                   href="{% url 'distribution:delete_message' object.pk %}">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/message_list.html
{% extends 'distribution/base.html' %}
{% load tags %}
{% block content %}
<div class="container-lg">
    <div class="row container">
        <div class="col-4"></div>
        <div class="col-4 text-center">
            <a type="button" class="btn btn-success mb-5 rounded-3 col-12"
               href="{% url 'distribution:create_message' %}">Создать cообщение</a>
        </div>
        <div class="col-4"></div>
        {% for object in object_list %}
        <div class="col-4 mb-4">
            <div class="card mb-4 rounded-3">
                <div class="card-header py-3  text-center">
                    <h4 class="my-0 fw-normal">{{object.title}}</h4>
                </div>
                <div class="card-body">
                    <p>
                        {{object.text|string_slice}}
                    </p>
                    {% if perms.distribution.change_mailingsettings or user == object.owner %}
                    <div class="card-footer">
                        <div class="row">
                            <div class="btn-group" role="group">
                                <a type="button" class="btn btn-outline-primary col-4"
                                   href="{% url 'distribution:message' object.pk %}">Подробнее</a>
                                <a type="button" class="btn btn-secondary col-4"
                                   href="{% url 'distribution:update_message' object.pk %}">Изменить</a>
                                <a type="button" class="btn btn-danger col-4"
                                   href="{% url 'distribution:delete_message' object.pk %}">Удалить</a>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}